#!/bin/bash
# Skript, mis väljastab mitu päeva antud hetkel masin on tööl
# Saame masina nime
masin=$(hostname)
# Saame serveri tööaja
info=$(uptime)
paeva=$(echo $info | awk '{print $3}')
tundi=$(echo $info | awk '{print $5}')
minutit=$(echo $info | awk '{print $6}')
# Väljastame tulemuse
echo "Masin $masin on töötanud $paeva päeva, $tundi tundi ja $minutit minutit."